credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$NEW_HASH_FOR_ADMIN  # Update with the new hash
    user:
      email: user@example.com
      name: Regular User
      password: $2b$12$NEW_HASH_FOR_USER  # Update with the new hash
cookie:
  expiry_days: 30
  key: 'your_secret_signature_key'  # Change this to a random string
  name: 'streamlit_auth_cookie' 
